### ISSUE TITLE
先切開再 Join 再切開是為了要做什麼嗎？

### ISSUE THREAD

**Issue by LarryLuTW** [wizenith/vscode_keybinding_from_vim#1]
在 `scanner.Scan()`  的迴圈開頭有一段是這樣的，先是把整行字（`scanner.Text()`）切開變成 current_line（型別是 []string），接著再丟進 `strings.SplitN(strings.Join(current_line, " "), " ", 3)` Join 之後再切開

https://github.com/wizenith/vscode_keybinding_from_vim/blob/5b4449cd560957c70e78dedcc8030f39ecd90236/main.go#L82-L83

為什麼不乾脆直接把 scanner.Text() 切三段就好了？

```go
match_arr := strings.SplitN(scanner.Text(), " ", 3) 
```

**Comment by wizenith** [comment]
這個問題問得好，因為我也是後來考慮到了一些特殊的情況需要處理後
例如若我們只用 `go strings.SplitN(scanner.Text(), " ", 3)`去切
當遇到了像前面留有很多空白的時候:
```             imap ;el <=``` 
切出來就會變成` [ (space) , (space) , imap ;el <=] ` 
因SplitN分三段並無法把前面不需要的空白處理掉，所以有必要先將前面的或中間可能不需要的空白除去掉
也就是一來有trim的效果，二來中間若有多個空白可以處理成一個空白
不過我不確定是不是應該用trim之類的method以及如何正確用trim來處理其他位置的多個空白
或者是否會有更好的方式來處理它

**Comment by LarryLuTW** [comment]
哦哦我的話應該就會用 trim
- 如果想要去掉頭尾的空白，那就直接用 [`bytes.TrimSpace(str)`](https://golang.org/pkg/bytes/#TrimSpace)
- 如果只想去掉開頭的空白，那就 [`bytes.TrimLeft(str, " ")`](https://golang.org/pkg/bytes/#TrimLeft)
- 如果希望去掉開頭的各種空白（\t、\n、\r 等等），那就 [`bytes.TrimLeftFunc(str, unicode.IsSpace)`](https://golang.org/pkg/bytes/#TrimLeftFunc)

Go 的 [`unicode.IsSpace`](https://golang.org/pkg/unicode/#IsSpace) 會把這些字元都判定成空白

<img width="854" alt="Screen Shot 2021-01-26 at 1 42 13 PM" src="https://user-images.githubusercontent.com/10403741/105805113-4d582c00-5fdc-11eb-95fc-7da0a54682d3.png">

**Comment by wizenith** [comment]
如果是用trim的話 那麼我的疑問會是要如何將中間多個的空白的情況處理成一個空白呢

**Comment by LarryLuTW** [comment]
哦哦原來你有這個需求，因為我想說 vimrc 應該（？）不太會有這種情況，如果你是因為這樣才 split 再 join 的話那我就覺得可以

不過 split 再 join 畢竟還是滿耗記憶體，所以我應該會用 regex，你可以參考看看這個 [Go Playground](https://play.golang.org/p/d-t_6sgHDgd)

```go
func removeDuplicateSpace(s string) string {
	spaces := regexp.MustCompile(`\s+`)
	return spaces.ReplaceAllString(s, " ")
}

func main() {
	s := "Hello  \t    \n world! \r   \n I am    Larry."
	s = removeDuplicateSpace(s)
	fmt.Println(s) // "Hello world! I am Larry."
}
```

**Comment by LarryLuTW** [comment]
補充一下，regex 裡的 `\s` 跟 `[ \f\n\r\t\v]` 等價，可以處理滿多種不同的空白

但如果自己 join 再 `split(' ')` 就只能處理最普通的空白（雖然 vimrc 裡面應該也不會有 `\t\v` 之類的啦XD）
