### ISSUE TITLE
這段程式碼應該不會執行到吧

### ISSUE THREAD

**Issue by LarryLuTW** [wizenith/vscode_keybinding_from_vim#2]
在 `splitFunc` 裡面有一段程式碼是這樣的，如果開頭是 `\n`，那就做 `dropCR`

https://github.com/wizenith/vscode_keybinding_from_vim/blob/5b4449cd560957c70e78dedcc8030f39ecd90236/main.go#L55-L59

但我看你的程式碼一開始就把他切成一行一行，所以開頭應該不可能是 `\n` 吧？

**Comment by wizenith** [comment]
對 你說的沒錯，原本這段程式碼是想要直接在里面去處理所有空白的問題(前面 Issue #1 有提到)
但因為我不知道該怎麼在Splitfunc里面去處理所有split需要處理的問題 後來我才會轉而在scanner.text()那段去處理一些我覺得比較棘手難以在splitfunc里處理的問題
基本上這段暫時是用不到了 但可以的話 我也還是很想把所有split上的問題都放到 splitfunc 里來處理

**Comment by LarryLuTW** [comment]
> 我也還是很想把所有split上的問題都放到 splitfunc 里來處理

我覺得 splitFunc 應該專心處理切字元的問題就好，空白、換行等等應該在剛 scan 進來就要 trim 好，才不會再切割的時候礙手礙腳的
