### ISSUE TITLE
為什麼是用 contain 而不是直接 ==

### ISSUE THREAD

**Issue by LarryLuTW** [wizenith/vscode_keybinding_from_vim#3]
關於第 86 行的部分我也有一個小疑問，為什麼是用 `strings.Contains` 而不是直接 `match_arr[0] == "inoremap" || match_arr[0] == "imap"` 呢

https://github.com/wizenith/vscode_keybinding_from_vim/blob/5b4449cd560957c70e78dedcc8030f39ecd90236/main.go#L86-L98

**Comment by wizenith** [comment]
對 我記得原本我還沒處理掉空白的問題時 我就先用這個
但其實你那樣是最簡單正確的，然後我想在這里問一下就是如果我想根據不同的mode來判斷並export出一個object如
 "vim.normalModeKeyBindingsNonRecursive": [{before: kv1, after: kv2}]
  "vim.normalModeKeyBindings": [{before: kv1, after: kv2}]
  "vim.insertModeKeyBindings": [{before: kv1, after: kv2}] 
  "vim.insertModeKeyBindingsNonRecursive":  [{before: kv1, after: kv2}] 
  "vim.visualModeKeyBindings": [{before: kv1, after: kv2}] 
  "vim.visualModeKeyBindingsNonRecursive":  [{before: kv1, after: kv2}] 
我應該采用 switch case 來處理嗎 那struct應該會長什麼樣子呢
