### ISSUE TITLE
如何將所有vim modes的keybindings各自處理成一組

### ISSUE THREAD

**Issue by wizenith** [wizenith/vscode_keybinding_from_vim#4]
目前我遇到了一個問題是我有試著建一個struct (如下)，然後在作scan的時候將各自不同的mode的keybinding收集起來
https://github.com/wizenith/vscode_keybinding_from_vim/blob/bb8660a6c0f1c289fb30b9f5c7bae82c9c3fef68/main.go#L20-L27

然而出現的結果是一組object里包含了所有vim模式的屬性 ( struct ), 
![image](https://user-images.githubusercontent.com/6877926/105937905-6e2e8900-6091-11eb-96ba-33c20d23bb5d.png)
我想要的格式是像這樣：
```json
  "vim.normalModeKeyBindingsNonRecursive": [
   
  ],
  "vim.normalModeKeyBindings": [
   
  ],
  "vim.insertModeKeyBindings": [
    {
      "before": ["i", "i"],
      "after": ["<Esc>"]
    }
  ],
  "vim.insertModeKeyBindingsNonRecursive": [
    
  ],
  "vim.visualModeKeyBindings": [
    {
      "before": [";"],
      "after": ["<Esc>"]
    },
    {
      "before": ["L"],
      "after": ["$"]
    },
    {
      "before": ["H"],
      "after": ["0"]
    },
    {
      "before": ["<"],
      "after": ["<", "g", "v"]
    },
    {
      "before": [">"],
      "after": [">", "g", "v"]
    },
   ],
  "vim.visualModeKeyBindingsNonRecursive": [
    {
      "before": [";", "c"],
      "after": ["\"", "k", "y"]
    },
  ],
```

**Comment by LarryLuTW** [comment]
看來你應該只需要 __一個__ `KeybindingsOfAllModes` struct 用來分類，然後裡面的每個屬性都是一個 `Keybinding` Array，所以你這邊的宣告就怪怪的，你並不需要 array of `KeybindingsOfAllModes`，你只需要一個

https://github.com/wizenith/vscode_keybinding_from_vim/blob/bb8660a6c0f1c289fb30b9f5c7bae82c9c3fef68/main.go#L74

應該改成 `var matchList KeybindingsOfAllModes`

然後根據每一行是什麼開頭把他們 append 進去對應的屬性

**Comment by LarryLuTW** [comment]
我剛剛 push 了一個新的 commit https://github.com/wizenith/vscode_keybinding_from_vim/commit/a53b84ff103c06462b8f5e178a2186d22a6502b1

只是我現在沒有幫你判斷開頭，全部塞在 Insert mode 裡面，這部分就留給你做了～
